name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # mvn clean package
          echo "Build"

      - name: Deploy to Dev
        run: |
          # Deploy to Dev environment
          echo "Deploying to Dev environment..."

  deploy-to-qa-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to QA
        run: |
          # Deploy to QA environment
          echo "Deploying to QA environment..."
        if: github.event.inputs.deploy_to_qa == 'true'

      - name: Deploy to Prod
        run: |
          # Deploy to Prod environment
          echo "Deploying to Prod environment..."
        if: github.event.inputs.deploy_to_prod == 'true'
