name: main

on:
  workflow_dispatch:
    inputs:
      approve:
        description: 'Approve deployment'
        required: true
        type: boolean

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.event.inputs.approve == 'true'
    steps:
      - name: Deploy to production
        run: echo deploying

