name: Workflow Two

on:
  workflow_run:
    workflows: ["Workflow One"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - qa
          - prod


jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to qa
        if: github.event.inputs.environment == 'qa'
        run: |
          # Deploy to prod environment here
      - name: Deploy to Prod
        if: github.event.inputs.environment == 'prod'
        run: |
          # Deploy to Prod environment
          echo "Deploying to Prod environment..."
